spring.datasource.url=jdbc:mysql://127.0.0.1:3306/skinsmarket?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

jwt.secret=clave-oculta-skinsmarket-2026-segura-extra-larga
jwt.expiration=86400000